<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>romer_publishers</name>
  <version>0.0.1</version>
  <description>Contains publishers and IK service for the romer_gazebo project</description>

  <maintainer email="support@franka.de">Franka Robotics GmbH</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>romer_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>kdl_parser</depend>
  <depend>urdf</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>